# Kibővített Magyar B2 Korpusz
EXPANDED_CORPUS = [
    "Szia, üdvözöllek az AI központban!",
    "Hogy érzed magad ma ebben a szép időben?",
    "A kedvenc nyelvem a magyar, mert nagyon kifejező.",
    "Szeretek új dolgokat tanulni a mesterséges intelligenciáról.",
    "Budapest egy csodálatos város, sok látnivalóval.",
    "Véleményem szerint a technológia segít az embereknek.",
    "Holnap találkozhatunk a kávézóban, ha van időd.",
    "Szeretnék egy pohár vizet kérni, nagyon megszomjaztam.",
    "Azt gondolom, hogy a nyelvtanulás fontos a jövőnk szempontjából.",
    "Milyen zenét szeretsz hallgatni munka közben?",
    "A családommal gyakran járunk kirándulni a Balatonhoz.",
    "Tudnál ajánlani egy jó éttermet a közelben?",
    "Sajnos elfelejtettem a telefonomat az irodában.",
    "Nagyon örülök a sikerednek, gratulálok a vizsgádhoz!",
    "A magyar konyha világhírű a finom ételeiről.",
    "Melyik a kedvenc könyved, amit legutóbb olvastál?",
    "Azt hiszem, ez a feladat nem is olyan nehéz, mint gondoltam.",
    "Szeretnék elutazni Japánba a jövő évben.",
    "A munkahelyemen mindenki nagyon kedves és segítőkész.",
    "Mikor kezdődik a koncert a téren?",
    "A barátaimmal tegnap este moziban voltunk.",
    "Szerintem a sport segít az egészség megőrzésében.",
    "El tudnád magyarázni, hogyan működik ez a gép?",
    "Nagyon szépen köszönöm a segítségedet, sokat jelent nekem.",
    "Várom már a hétvégét, hogy végre pihenhessek egy kicsit.",
    "A tanulás néha fárasztó, de megéri a befektetett energiát.",
    "Milyen érdekes ez a cikk a legújabb tudományos felfedezésekről!",
    "Szeretném megkérdezni, hogy mikor érkezik meg a csomagom.",
    "A természet lágy ölén lenni mindig feltölt energiával.",
    "Remélem, hamarosan újra találkozunk és beszélgetünk.",
    "A kávé illata mindig jókedvre derít reggelente.",
    "Milyen sűrűn jársz edzőterembe vagy futni?",
    "Azt hallottam, hogy holnap esni fog az eső.",
    "Kérlek, ne haragudj, hogy ilyen sokat késtem.",
    "Ez a sütemény egyszerűen mennyei, kérek még belőle.",
    "A technikai fejlődés alapjaiban változtatja meg az életünket.",
    "Szeretek olvasni a történelemről és a nagy hódítókról.",
    "Milyen messze van innen a legközelebbi benzinkút?",
    "Azt tervezem, hogy megtanulok gitározni ezen a nyáron.",
    "A barátság az egyik legfontosabb dolog az életben.",
    "Mindig próbálok pozitívan hozzáállni a problémákhoz.",
    "Melyik a legkedvesebb emléked a gyerekkorodból?",
    "Azt hiszem, eltévedtünk, meg kellene néznünk a térképet.",
    "Szívesen segítek neked bármiben, fordulj hozzám bizalommal.",
    "A holnapi megbeszélést elhalasztották jövő hétre.",
    "Nagyon tetszik a stílusod, mindig jól öltözött vagy.",
    "Milyen érzés volt először repülővel utazni?",
    "Szeretem a friss gyümölcsök és zöldségek ízét.",
    "A türelem rózsát terem, tartja a régi magyar közmondás.",
    "Minden nap teszek valamit azért, hogy jobb ember legyek."
]
